# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37d23ffda0bc9282705b4df483cd21f69d70e9a0f389cb43381fcfd25b6bf19151c6d58c7c48606f1c71c8f65135cc3833c0677635f0710cea3e8ce5ae36305

test:
  secret_key_base: b71c9815aa8f53820786b2ad84155e939947b70bc0a5e1f39465cbb037f488ed1efbc33c3d69a1d36557d0e12368d0a86889a9c775f9f03d7bfca8a95aa43875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
